language: clojure
lein: 2.8.1
sudo: false
cache:
  directories:
    - $HOME/.m2
script: make $TARGET
env:
  matrix:
    - VERSION=1.9 TARGET=test
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
stages:
  - name: check
    jdk: openjdk11
  - name: test
jobs:
  include:
    # Test latest OpenJDK against latest Clojure stable
    - env: VERSION=1.9 TARGET=test
      jdk: openjdk8

    # Test Clojure master against a single JDK
    - env: VERSION=master TARGET=test
      jdk: openjdk11

    # Coverage analysis
    - env: VERSION=1.9 TARGET=cloverage
      jdk: openjdk11
      after_success: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

    # Eastwood linter
    - stage: check
      env: VERSION=1.9 TARGET=eastwood

    # Check cljfmt
    - stage: check
      env: VERSION=1.9 TARGET=cljfmt

  fast_finish: true      # don't wait for allowed failures before build finish
  allow_failures:
    - jdk: openjdk-ea
    - env: VERSION=master TARGET=test
    - env: VERSION=1.9 TARGET=cloverage
