dist: xenial
language: clojure
lein: 2.8.3
cache:
  directories:
    - $HOME/.m2
script: make $TARGET
env:
  matrix:
    - VERSION=1.8 TARGET=test
    - VERSION=1.9 TARGET=test
    - VERSION=1.10 TARGET=test
    - VERSION=master TARGET=test
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
stages:
  - name: check
  - name: test
jobs:
  include:
    - stage: check
      jdk: openjdk11
      env: VERSION=1.10 TARGET=eastwood

    - stage: check
      jdk: openjdk11
      env: VERSION=1.10 TARGET=cljfmt

    - stage: test
      env: VERSION=1.9 TARGET=cloverage
      jdk: openjdk11
      after_success: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk-ea
    - env: VERSION=master TARGET=test
    - env: VERSION=1.10 TARGET=eastwood
    - env: VERSION=1.10 TARGET=cloverage
